# Generated by Django 4.0.2 on 2022-04-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_theme'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Language',
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['-id'], 'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='category',
            new_name='language',
        ),
        migrations.AddField(
            model_name='post',
            name='theme',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='main.theme'),
            preserve_default=False,
        ),
    ]
